sudo: required
services:
 - docker

before_install:
 - docker build -t sksn12282881/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true sksn12282881/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ca-central-1'
  app: 'docker-react'
  env: 'dockerreact-env-1'
  bucket_name: 'elasticbeanstalk-ca-central-1-672458883776'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


